### ISSUE TITLE
tbar - bar too slight and not matching t

### ISSUE THREAD

**Issue by EbenSorkin** [aoifemooney/anaheimFont#14]

**Comment by aoifemooney** [comment]
This was an optical compensation. When bar is same weight as cross stroke, shape feels heavy. However, the t that was a decomposed 't' seems to be a legacy form, so I updated with the most recent form, and replaced the bars in both weights to better fit the width. In the bold, I compensated both the crossbar and the bar to lighten the shape. I think it works better now. Marking as resolved.
